### ISSUE TITLE
Migrate away from discord.py

### ISSUE THREAD

**Issue by akrantz01** [WaffleHacks/wafflebot#7]
Seeing as the Discord bot library we use ([discord.py](https://github.com/Rapptz/discord.py)) has been officially discontinued, we should move away from it to some other library. [Here](https://gist.github.com/Rapptz/4a2f62751b9600a31a0d3c78100287f1) is the official statement from the author on why it is being discontinued.

This would also be a good time for implementing slash commands and the interactions API (#4). Given Discord's current stance, we must implement slash commands by April 2022.

Potential replacement libraries grouped by slash command implementation status:
  - Implemented
    - [Serenity](https://github.com/serenity-rs/serenity) (Rust)
    - [JDA](https://github.com/DV8FromTheWorld/JDA) (Java)
    - [discord.js](https://discord.js.org/#/) (JavaScript)
    - [kord](https://github.com/kordlib/kord) (Kotlin)
    - [nostrum](https://github.com/kraigie/nostrum) (Elixir)
    - [dimscord](https://github.com/krisppurg/dimscord) (Nim)
    - [discord-interactions](https://github.com/goverfl0w/discord-interactions) (Python)
  - Partial
    - [discordgo](https://github.com/bwmarrin/discordgo) (Golang)
    - [discordrb](https://github.com/discordrb/discordrb) (Ruby)
    - [Eris](https://github.com/abalabahaha/eris) (JavaScript)
    - [Discordia](https://github.com/sinisterrectus/discordia) (Lua)

**Comment by krisppurg** [comment]
Author of dimscord here, just here to add: we do have slash commands implemented (incl. context menus, permissions, etc), you can update your list.

**Comment by akrantz01** [comment]
Ah, good to know, thanks. I was using [this gist](https://gist.github.com/Rapptz/4a2f62751b9600a31a0d3c78100287f1#wont-things-be-fine-in-april-2022-theres-enough-time) as a reference for my list.
